/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { DaoAuthorizable } from "./DaoAuthorizable";
export type { DaoAuthorizableUpgradeable } from "./DaoAuthorizableUpgradeable";
