/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IPluginRepo } from "./IPluginRepo";
export type { PluginRepo } from "./PluginRepo";
export type { PluginRepoRegistry } from "./PluginRepoRegistry";
