/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { PluginCloneableSetupV1Mock__factory } from "./PluginCloneableSetupV1Mock__factory";
export { PluginCloneableSetupV1MockBad__factory } from "./PluginCloneableSetupV1MockBad__factory";
export { PluginCloneableSetupV2Mock__factory } from "./PluginCloneableSetupV2Mock__factory";
