/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type {
  Multicallable,
  MulticallableInterface,
} from "../../../../../@ensdomains/ens-contracts/contracts/resolvers/Multicallable";
import { Contract, Interface, type ContractRunner } from "ethers";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes[]",
        name: "data",
        type: "bytes[]",
      },
    ],
    name: "multicall",
    outputs: [
      {
        internalType: "bytes[]",
        name: "results",
        type: "bytes[]",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes4",
        name: "interfaceID",
        type: "bytes4",
      },
    ],
    name: "supportsInterface",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
] as const;

export class Multicallable__factory {
  static readonly abi = _abi;
  static createInterface(): MulticallableInterface {
    return new Interface(_abi) as MulticallableInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): Multicallable {
    return new Contract(address, _abi, runner) as unknown as Multicallable;
  }
}
