/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as setup from "./setup";
export { IPlugin__factory } from "./IPlugin__factory";
export { Plugin__factory } from "./Plugin__factory";
export { PluginCloneable__factory } from "./PluginCloneable__factory";
export { PluginUUPSUpgradeable__factory } from "./PluginUUPSUpgradeable__factory";
