/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../../../common";
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";

export declare namespace PermissionLib {
  export type MultiTargetPermissionStruct = {
    operation: BigNumberish;
    where: AddressLike;
    who: AddressLike;
    condition: AddressLike;
    permissionId: BytesLike;
  };

  export type MultiTargetPermissionStructOutput = [
    operation: bigint,
    where: string,
    who: string,
    condition: string,
    permissionId: string
  ] & {
    operation: bigint;
    where: string;
    who: string;
    condition: string;
    permissionId: string;
  };
}

export declare namespace IPluginSetup {
  export type PreparedSetupDataStruct = {
    helpers: AddressLike[];
    permissions: PermissionLib.MultiTargetPermissionStruct[];
  };

  export type PreparedSetupDataStructOutput = [
    helpers: string[],
    permissions: PermissionLib.MultiTargetPermissionStructOutput[]
  ] & {
    helpers: string[];
    permissions: PermissionLib.MultiTargetPermissionStructOutput[];
  };

  export type SetupPayloadStruct = {
    plugin: AddressLike;
    currentHelpers: AddressLike[];
    data: BytesLike;
  };

  export type SetupPayloadStructOutput = [
    plugin: string,
    currentHelpers: string[],
    data: string
  ] & { plugin: string; currentHelpers: string[]; data: string };
}

export interface PlaceholderSetupInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "implementation"
      | "prepareInstallation"
      | "prepareUninstallation"
      | "prepareUpdate"
      | "protocolVersion"
      | "supportsInterface"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "implementation",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "prepareInstallation",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "prepareUninstallation",
    values: [AddressLike, IPluginSetup.SetupPayloadStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "prepareUpdate",
    values: [AddressLike, BigNumberish, IPluginSetup.SetupPayloadStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "protocolVersion",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "implementation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "prepareInstallation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "prepareUninstallation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "prepareUpdate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "protocolVersion",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
}

export interface PlaceholderSetup extends BaseContract {
  connect(runner?: ContractRunner | null): PlaceholderSetup;
  waitForDeployment(): Promise<this>;

  interface: PlaceholderSetupInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  implementation: TypedContractMethod<[], [string], "view">;

  prepareInstallation: TypedContractMethod<
    [arg0: AddressLike, arg1: BytesLike],
    [[string, IPluginSetup.PreparedSetupDataStructOutput]],
    "view"
  >;

  prepareUninstallation: TypedContractMethod<
    [arg0: AddressLike, arg1: IPluginSetup.SetupPayloadStruct],
    [PermissionLib.MultiTargetPermissionStructOutput[]],
    "view"
  >;

  prepareUpdate: TypedContractMethod<
    [
      _dao: AddressLike,
      _fromBuild: BigNumberish,
      _payload: IPluginSetup.SetupPayloadStruct
    ],
    [[string, IPluginSetup.PreparedSetupDataStructOutput]],
    "nonpayable"
  >;

  protocolVersion: TypedContractMethod<[], [[bigint, bigint, bigint]], "view">;

  supportsInterface: TypedContractMethod<
    [_interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "implementation"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "prepareInstallation"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BytesLike],
    [[string, IPluginSetup.PreparedSetupDataStructOutput]],
    "view"
  >;
  getFunction(
    nameOrSignature: "prepareUninstallation"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: IPluginSetup.SetupPayloadStruct],
    [PermissionLib.MultiTargetPermissionStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "prepareUpdate"
  ): TypedContractMethod<
    [
      _dao: AddressLike,
      _fromBuild: BigNumberish,
      _payload: IPluginSetup.SetupPayloadStruct
    ],
    [[string, IPluginSetup.PreparedSetupDataStructOutput]],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "protocolVersion"
  ): TypedContractMethod<[], [[bigint, bigint, bigint]], "view">;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[_interfaceId: BytesLike], [boolean], "view">;

  filters: {};
}
