/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { PermissionConditionMock__factory } from "./PermissionConditionMock__factory";
export { PermissionManagerTest__factory } from "./PermissionManagerTest__factory";
