/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../../../common";
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";

export declare namespace IPlugin {
  export type TargetConfigStruct = {
    target: AddressLike;
    operation: BigNumberish;
  };

  export type TargetConfigStructOutput = [target: string, operation: bigint] & {
    target: string;
    operation: bigint;
  };
}

export interface PluginV1MockInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "SET_TARGET_CONFIG_PERMISSION_ID"
      | "dao"
      | "getCurrentTargetConfig"
      | "getTargetConfig"
      | "pluginType"
      | "protocolVersion"
      | "setTargetConfig"
      | "state1"
      | "supportsInterface"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "TargetSet"): EventFragment;

  encodeFunctionData(
    functionFragment: "SET_TARGET_CONFIG_PERMISSION_ID",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "dao", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getCurrentTargetConfig",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTargetConfig",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "pluginType",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "protocolVersion",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setTargetConfig",
    values: [IPlugin.TargetConfigStruct]
  ): string;
  encodeFunctionData(functionFragment: "state1", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "SET_TARGET_CONFIG_PERMISSION_ID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "dao", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getCurrentTargetConfig",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTargetConfig",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "pluginType", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "protocolVersion",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTargetConfig",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "state1", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
}

export namespace TargetSetEvent {
  export type InputTuple = [newTargetConfig: IPlugin.TargetConfigStruct];
  export type OutputTuple = [newTargetConfig: IPlugin.TargetConfigStructOutput];
  export interface OutputObject {
    newTargetConfig: IPlugin.TargetConfigStructOutput;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PluginV1Mock extends BaseContract {
  connect(runner?: ContractRunner | null): PluginV1Mock;
  waitForDeployment(): Promise<this>;

  interface: PluginV1MockInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  SET_TARGET_CONFIG_PERMISSION_ID: TypedContractMethod<[], [string], "view">;

  dao: TypedContractMethod<[], [string], "view">;

  getCurrentTargetConfig: TypedContractMethod<
    [],
    [IPlugin.TargetConfigStructOutput],
    "view"
  >;

  getTargetConfig: TypedContractMethod<
    [],
    [IPlugin.TargetConfigStructOutput],
    "view"
  >;

  pluginType: TypedContractMethod<[], [bigint], "view">;

  protocolVersion: TypedContractMethod<[], [[bigint, bigint, bigint]], "view">;

  setTargetConfig: TypedContractMethod<
    [_targetConfig: IPlugin.TargetConfigStruct],
    [void],
    "nonpayable"
  >;

  state1: TypedContractMethod<[], [bigint], "view">;

  supportsInterface: TypedContractMethod<
    [_interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "SET_TARGET_CONFIG_PERMISSION_ID"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "dao"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getCurrentTargetConfig"
  ): TypedContractMethod<[], [IPlugin.TargetConfigStructOutput], "view">;
  getFunction(
    nameOrSignature: "getTargetConfig"
  ): TypedContractMethod<[], [IPlugin.TargetConfigStructOutput], "view">;
  getFunction(
    nameOrSignature: "pluginType"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "protocolVersion"
  ): TypedContractMethod<[], [[bigint, bigint, bigint]], "view">;
  getFunction(
    nameOrSignature: "setTargetConfig"
  ): TypedContractMethod<
    [_targetConfig: IPlugin.TargetConfigStruct],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "state1"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[_interfaceId: BytesLike], [boolean], "view">;

  getEvent(
    key: "TargetSet"
  ): TypedContractEvent<
    TargetSetEvent.InputTuple,
    TargetSetEvent.OutputTuple,
    TargetSetEvent.OutputObject
  >;

  filters: {
    "TargetSet(tuple)": TypedContractEvent<
      TargetSetEvent.InputTuple,
      TargetSetEvent.OutputTuple,
      TargetSetEvent.OutputObject
    >;
    TargetSet: TypedContractEvent<
      TargetSetEvent.InputTuple,
      TargetSetEvent.OutputTuple,
      TargetSetEvent.OutputObject
    >;
  };
}
