/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as pluginCloneableMockSol from "./PluginCloneableMock.sol";
export * as pluginCloneableSetupMockSol from "./PluginCloneableSetupMock.sol";
